image: zhanxw/rvtests.build:latest
before_script:
    - export http_proxy=http://proxy.swmed.edu:3128
    - export https_proxy=http://proxy.swmed.edu:3128
    - export ftp_proxy=http://proxy.swmed.edu:3128
    - export no_proxy="127.0.0.1,localhost"
    - uname -a
    - free -m
    - df -h
    - ulimit -a
stages:
    - build
    - deploy
job1:
    stage: build
    script:
        - make
job2:
    stage: deploy
    script:
        - echo "Packing RVTESTS"
        - make
        - FN=/dist/rvtests-`date +"%Y%m%d"`-`git rev-parse HEAD|cut -c 1-6`-linux64-static.tar.gz; cd .. && tar zvcf ${FN} rvtests/executable/rvtest rvtests/executable/vcf2kinship rvtests/example rvtests/README.md && echo "Output file name is ${FN}"
    environment:
        name: staging
        url: http:staging-rvtests.bunny.swmed.edu
    when: "manual"
