env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "tCnbR5qSmTKnX4INhymQNdodn3U6VunImiSrM9/mFI0IoxDBPMF+NXBxkQdPD1BjKwb8qmqX3gKXUmxjZWAg5JSypUdg9M0iDyTYd6pPXyS2wa/jrbfrjtMkoE7bQejaY8gjmcA96d0Td7NHcAhw5A0qq5Z3WspdpzldusQcq6M="
language: cpp
matrix:
  include:
  - env: PLATFORM='linux64'
    os: linux
    dist: trusty
    sudo: required
    compiler: gcc
  - env: PLATFORM='windows32'
    os: linux
    dist: xenial 
    sudo: required
    compiler: gcc
  - env: PLATFORM='macos'
    os: osx
    osx_image: xcode8
    compiler: clang
  - env: PLATFORM='musl64'
    os: linux
    dist: trusty
    sudo: required
    compiler: gcc
before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then free -m; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then vm_stat; fi
  - df -h
  - ulimit -a
  - TARGET="${PLATFORM::${#PLATFORM}-2}"
  - "./build/${TARGET}/requirements.sh"
install:
  - source ./build/${TARGET}/build.sh
script:
  - echo "Nothing."
before_deploy:
  - mkdir -p dist
  - "./build/${TARGET}/package.sh"
deploy:
  provider: releases
  api_key:
    secure: ILnaYSSn9uaRUq8g0UOoAwdltVx9Qy/B7DPlt4ANMV3f4oxW9I7IotPnGcUpi7SzCAR9FlH9Drpct7awBWCXHRd9bp8nfhRnqnjwymhuyO08xkMYcdu3+TE5SjtKWnicakJZqwgAeUl0YSsEOl0M0A5LShKaFTn55tNQ/PPZe28=
  file:
    - "$(ls dist/*tar.gz dist/*.zip)"
  skip_cleanup: true
  on:
    repo: zhanxw/rvtests
    branch: master
    tags: true

addons:
  coverity_scan:
    project:
      name: "zhanxw/rvtests"
      description: "Rare variant test software for next generation sequencing data"
    notification_email: zhanxw@gmail.com
    build_command_prepend: "uname -a"
    build_command: "make"
    branch_pattern: coverity_scan
